---
title: 'Modesty'
author: "Brian Weatherson"
date: "October 25, 2021"
output:
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    latex_engine: xelatex
geometry: margin=1.4in
mainfont: SF Pro Text Light
mainfontoptions: BoldFont = SF Pro Text Medium
mathfont: Fira Math
header-includes: \linespread{1.17}
---

## Organising Questions

1. Is Modesty purely mental, purely behavioural, or some mixture of the two?
2. Does Modesty require an asymmetry in how one thinks of oneself versus others?
3. Are Modesty and Humility the same thing, or are they different things?
4. Is Modesty about various domains (e.g., about one's ability at chess) more fundamental than Modesty _tout court_, or is this 'absolute' Modesty the fundamental notion - or neither?
5. How does the notion of Modesty at issue in ethics papers relate to sexual modesty and/or intellectual modesty?

## Behaviour

Assume that Modesty is all about mental states, as most theories seem to suggest. Then consider the following two cases.

- A has the behavioural profile of someone who is Modest. (They don't brag, draw attention to their successes, show irritation with people who don't acknowledge their success etc.) But they don't have the right mental profile at all. Deep down, they think they are the greatest. But they believe it would be wrong to act that way - it would make others feel bad about themselves and they don't want to cause those bad feelings out of consideration for other people - so they act as if they were Modest. Is this Modesty or false Modesty?
- B has the perfect mental profile of a Modest person. But they believe that the social norms where they are require one to not act as if one is Modest. They believe those norms require self-aggrandisement and other behaviour typical of the imModest person. Is B Modest? Does it matter whether their beliefs about the norms are correct?

Bommarito argues that Modesty can't be behavioural as follows.

> Theories of modesty also need to be able to distinguish modesty from false modesty. That is, some people who are not modest can act as if they are. This rules out accounts of modesty that are entirely behavioral. If being modest is simply a matter of certain external behaviors, then there would be no way to distinguish modesty from false modesty. Modesty and humility require certain mental states in addition to overt behaviors.

This seems much too quick to me. The second sentence is question-begging if this is meant to be an argument. And if the challenge is how can a behavioural theory of Modesty can provide for the possibility of false Modesty, that seems easy. To be Modest is to be disposed to generally act as if one's achievements are no big deal. (Or something like that - what matters is the disposition.) False Modesty is not having that disposition in general, but merely being disposed to act that way in high profile or high stakes situations.

On this view there are instances of false Modesty, but not really such a thing as global false Modesty. False Modesty requires some imModest dispositions. But that seems plausible to me.

## Asymmetry

Assume again that Modesty is purely mental. Maybe it's a matter of underestimating oneself, or not over-estimating oneself, or not caring whether one is valued for achievements, or whatever. Call the relevant attitude M, and consider this case.

- C has attitude M towards all people who are great at chess. They don't value being great at chess, they don't care whether people who are great at chess are valued, and so on. But they do enjoy chess. And because they enjoy it, they play it a lot, and eventually get very good. But they keep attitude M towards all people who are good at chess, including now themselves. Is C Modest about their chess abilities?

It seems to me that they aren't. Modesty is essentially self-directed. If one has an attitude towards a group, and then it turns out, almost by accident, that one is in the group, that can't be enough for Modesty.

In general, there is surprisingly little about the self in the various theories of Modesty. All of them seem to have this feature that one could be Modest by having a general disposition towards a group and then finding oneself in the group. And that doesn't feel like enough.

## Modesty and Humility

This could end up being largely word-play, but maybe there is an interesting question here. Are these two the same thing?

I don't have a ton to say here, other than that the authors we've read seem to skim over the question surprisingly quickly. If I had to guess, I'd say Humility was more mental and Modesty was more behavioural. But most authors can't say that - they think Modesty is basically mental.

## Domain-Specific Modesty

Schueler suggests, without I think arguing for, the following picture. The fundamental logical form of Modesty statements is not _X is Modest_, but _X is Modest about Y_. To the extent that we can even understand the unqualified statement, it should be thought of as something like a limiting case, or as shorthand for something like _X is Modest about themselves_.

We certainly do have in natural language expressions like _X is Modest about their successes in chess_. And we can imagine people who are Modest in one domain but very imModest in another domain. But should we think that being Modest about something is the primary notion?

I don't really have a firm view here, or even for that matter a sense of what would settle the matter. But it's worth thinking through some edge cases to clarify the issues. So imagine this example:

- D has a few distinct impressive accomplishments. When anyone brings up any of these except their favorite one, they play it down by changing the conversation back to how impressive that particular achievement was.

I think D is not at all Modest. But I think on a bunch of views they'll end up being Modest about all their achievements but one. That seems maybe a bit wrong, so I'm a little inclined to think the absolute sense of Modesty is prior. Or here's another relevant case.

- E doesn't have any notable achievements to speak of. But this is too bad, because they are disposed to downplay (both internally and externally) any achievements they get, and not use these as reasons for thinking or acting that they are better than anyone else.

I guess I think E is Modest, but not Modest about anything, which is also a challenge for the view that Modesty is a dependent virtue.

## Varieties of Modesty

We will talk a lot next week about Intellectual Modesty, or perhaps better Intellectual Humility. For now I just want to ask about how these three notions relate.

- Modesty in whatever sense we're interested in here.
- Intellectual Modesty
- Sexual Modesty

The standard line in the philosophical literature is that sexual Modesty is a distinct notion. I suspect this is based on a misunderstanding of the folk ethics of sexual Modesty. I think the folk view is that good looks are either an achievement, or a virtue, or at the very least a sign of achievement or virtue. (I don't mean this to be a unified view - just that many people believe one of these disjuncts.) What we normally call sexual Modesty is, from this perspective, not bragging. It's deliberately showing off the virtues or achievements you have. So it isn't really a distinct category. 

Intellectual Modesty is a different thing, but here it is interesting to think about whether some people might take it to be the primary notion. I was struck that Benjamin Franklin's version of _Be Modest!_ was _Be like Jesus or Socrates!_. Because they are not examples of what I would call Modest people. I don't get the reference to Jesus at all, but let's think about Socrates. He does have a sort of Intellectual Humility, a weird sort but still a sort. But he doesn't have any of the traditional sorts of Modesty. He seems to be very confident that he doesn't act wrongly, for example. Now he does credit this to a guardian angel rather than to himself, but still it doesn't sound Modest to me. I think what's going on here is that Franklin is taking Intellectual Modesty to be basic, and since Socrates thought he knew very little, he qualifies as Modest. 

Should we think of Intellectual Modesty as the fundamental kind? Maybe this is something to come back to after we discuss what Intellectual Modesty is.

## Driver's View

Driver takes Modesty to be a certain kind of ignorance of one's own qualities.  The big challenge to Driver, and one we should discuss, is why we should think of this as a virtue. Driver is a consequentialist, who thinks a virtue just is a character trait that typically has good consequences. And it is clear that this character trait might have good consequences - it reduces jealousy, envy etc. But is that enough to make it a virtue.

I'd also like us to go over a bunch of possible puzzle cases for Driver's view. Let's start with one that's similar to C above.

- F systematically undervalues acts of generosity. They notice when people are generous, but they don't credit people that much for it. One day they do something very generous, but in keeping with their general attitude to generosity, they don't give themselves much credit for it.

I don't think this makes F Modest, though they are Modest on Driver's account. Here's a somewhat similar example.

- G is a very good novelist, but hardly the best in the world. G also thinks they have no ability at all to tell who is a good or bad novelist. If you ask them where they think any particular novelist ranks, they'll say "No idea. Could be the best, could be the worst, I'm no good at telling this." And they'll say that about themselves just like they will say it about anyone else. 

Is G Modest about their novel-writing ability? I don't think they are. They are Modest about something else, namely their ability to tell good novelists from bad ones. But they aren't Modest about their ability. They really think they might be the best in the world!

But you might think this isn't really a problem for Driver's view. While G is **ignorant** of their novel writing ability, they don't **under-estimate** it. And that's what Driver stresses, under-estimation. (So why is it called an ignorance account?) Actually it's worth separating out four separate views, because I think it's a bit funny which one Driver thinks is Modesty.

1. X is Modest about F if X is good at F but X's belief about how good they are is lower than how good they actually are.
2. X is Modest about F if X is good at F but X's belief about how good they are (as a person) in virtue of being this good at X is lower than how good they actually are (as a person) in virtue of being this good at F.
3. X is Modest about F if X is good at F but X doesn't realise how good they are at F.
4. X is Modest about F if X is good at F but X doesn't realise how good they are (as a person) in virtue of being good at F.

I think Driver's view is option 1. (Do you agree? We probably should clarify this!) But I kind of think it's one of the least plausible of the four options. Consider, for example, this way of separating out 1 and 2.

- H is a great chess player. Many people think the best in the world. But if you talk to H about their chess skill they will say, completely sincerely, "Well yes I do win plenty of games. But it's just pushing some pieces around a board - it's not like I cured cancer or something". That is, they believe (truly) that they are incredibly good at chess, but don't think this is something that really matters.

On option 1, they are not Modest, on option 2 they are. I think they really are Modest, so this is a reason to prefer option 2.

The case of G might be taken to suggest that option 3 is worse than option 1. But I'm not entirely sure that's right. One thing that seems attractive about Driver's view is the idea that Modesty involves sort of not attending to one's own skills. There's something nice about the Modest person being the kind of person who, when you point out to them how good they are at something, says "I guess you're right, I just hadn't been thinking about the comparison." But Driver, I think, wants the Modest person to be thinking about comparisons and get them wrong. Option 3, which allows for not making the comparisons, seems better.

Finally, here's one case that I think is very hard for Driver, and which leads naturally into some issues for Schueler.

- J is a great football player, one of the best in the world. J also believes, correctly, that they are one of the best in the world. And since they highly value football, they think this is a very good thing to be. But if you talk to J about their skill they will say, completely sincerely, that they themselves only played a relatively small part in their success. If it wasn't for a whole team, from parents to early coaches to a larger system that supported them, they wouldn't be anywhere, and that the vast bulk of the credit for their success should be spread across this team. All these beliefs they have are true.

I think J is Modest in the sense we most care about. But they don't underestimate themselves in any respect. What should Driver say about such a person.

## Schueler

This is going on a bit long already, but I wanted to note one tension within Schueler's view. It's helpful to bring it out by thinking about this case of J, and relating it to the theological view that Schueler discusses. Schueler needs the following things to be true.

1. Many people have "genuine accomplishments".
2. The credit for these accomplishments doesn't go to them.

Schueler mentions three reasons that you might support 2, and endorses (I think) two of them. The first is that the credit all goes to God. That's the one he doesn't endorse. The second is that the accomplishments aren't that big a deal in the overall scheme of things. He seems at times a bit sympathetic to this. The third is that the credit for the accomplishment shouldn't go to the person who performed the act, but to the 'broader ecosystem'. And this one he more strongly endorses. So we get someone like J being the paradigm of a Modest person.

But what I don't get is why he thinks this is consistent with 1. Once you see that J's success at football comes from things that don't rebound to J's credit, then why think it is even a "genuine accomplishment"? I guess I don't see why we should think that the view he puts forward at the end is that different from the 'low-ranking' assumption on views that he wants to reject.

That's not to say this is a false view. I'm inclined to think it largely is true. Indeed, I think Schueler himself should notice it more. Think about when he says that sometimes you can't doubt how much of an accomplishment you have - you either set the world record or you didn't. But you can doubt how much of the accomplishment _you_ did, and how much is a team effort. So I think the "credit usually goes to the broader team" view is probably right. But I don't see how that lets Schueler have a different view to Flanagan and others.